/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HelloWorldImport } from './routes/hello-world'
import { Route as IndexImport } from './routes/index'
import { Route as HelloNameImport } from './routes/hello.$name'

// Create/Update Routes

const HelloWorldRoute = HelloWorldImport.update({
  id: '/hello-world',
  path: '/hello-world',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HelloNameRoute = HelloNameImport.update({
  id: '/hello/$name',
  path: '/hello/$name',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/hello-world': {
      id: '/hello-world'
      path: '/hello-world'
      fullPath: '/hello-world'
      preLoaderRoute: typeof HelloWorldImport
      parentRoute: typeof rootRoute
    }
    '/hello/$name': {
      id: '/hello/$name'
      path: '/hello/$name'
      fullPath: '/hello/$name'
      preLoaderRoute: typeof HelloNameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hello-world': typeof HelloWorldRoute
  '/hello/$name': typeof HelloNameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hello-world': typeof HelloWorldRoute
  '/hello/$name': typeof HelloNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/hello-world': typeof HelloWorldRoute
  '/hello/$name': typeof HelloNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hello-world' | '/hello/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hello-world' | '/hello/$name'
  id: '__root__' | '/' | '/hello-world' | '/hello/$name'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelloWorldRoute: typeof HelloWorldRoute
  HelloNameRoute: typeof HelloNameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelloWorldRoute: HelloWorldRoute,
  HelloNameRoute: HelloNameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/hello-world",
        "/hello/$name"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/hello-world": {
      "filePath": "hello-world.tsx"
    },
    "/hello/$name": {
      "filePath": "hello.$name.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
